FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o db ./cmd/db

# ---- runtime ----
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/db /app/db

EXPOSE 8081

CMD ["/app/db"]
